 # Deep Learning (Học sâu)

## PyTorch cơ bản

Ghi chú: Notebook này chứa các ví dụ cơ bản về PyTorch và cách xử lý bộ dữ liệu Iris bằng pandas, scikit-learn và PyTorch.

In [2]:
# import thư viện PyTorch
import torch

In [3]:
# Kiểm tra xem CUDA (GPU) có sẵn không
torch.cuda.is_available()

False

Dataset với PyTorch

Sử dụng bộ dữ liệu Iris làm ví dụ để minh hoạ cách đọc dữ liệu, tiền xử lý và chuẩn bị cho mô hình PyTorch.

In [ ]:
import torch
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [22]:
# Đọc bộ dữ liệu Iris và hiển thị vài dòng đầu
df = pd.read_csv('Iris.csv')
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [23]:
# Kiểm tra kích thước dataset (số hàng, số cột)
df.shape

(150, 6)

In [24]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

le = LabelEncoder()
X = df.drop(['Species'], axis=1).values 
y = le.fit_transform(df['Species'].values)

# Chia dữ liệu với test size = 20%
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)
y_train = torch.LongTensor(y_train).reshape(-1,1) 
y_test = torch.LongTensor(y_test).reshape(-1,1)


In [25]:
len(y_train)

120

In [26]:
labels, counts = y_train.unique(return_counts=True)
print(labels,counts)

tensor([0, 1, 2]) tensor([40, 41, 39])


In [ ]:
# Tính đọa hàm bằng pyTorch

# Cho y = 2x^4  + x^3 + 3x^2 + 5x + 1

# Tính y'

In [27]:
import torch

In [28]:
x = torch.tensor(2.0, requires_grad=True)
print(x)
print(x.grad)

tensor(2., requires_grad=True)
None


In [29]:
#Định nghỉa hàm y
y = 2 * x**4 + x**3 + 3*x**2 + 5*x + 1
print(y)


tensor(63., grad_fn=<AddBackward0>)


In [30]:
y.grad_fn

In [ ]:
# Thực hiện lan truyền ngược và tính toán cá gradient
y.backward()

In [32]:
# 8x^3 + 3x^2 + 6x + 5 
x.grad

tensor(93.)

# Bài Tập Về Nhà 01 :
Tính đạo hàm của hàm số y = 3x^5 + 2x^4 + x^3 + 4x + 7 tại x = 3 sử dụng PyTorch
Cho x = 5x^5 + 6x^3 -3x +1 
Cho biết độ dốc của đa thức trên ở điểm nào 

In [ ]:
import torch

# y = 3x^5 + 2x^4 + x^3 + 4x + 7 tại x=3
x1 = torch.tensor(3.0, requires_grad=True)
y1 = 3*x1**5 + 2*x1**4 + x1**3 + 4*x1 + 7
y1.backward()
print("y'(3) =", x1.grad.item())  
# y = 5x^5 + 6x^3 - 3x + 1: điểm có độ dốc = 0
def slope(x_val):
    x = torch.tensor(float(x_val), requires_grad=True)
    y = 5*x**5 + 6*x**3 - 3*x + 1
    y.backward()
    return x.grad.item()
print("Điểm dốc=0: x≈+0.3736, y' =", slope(0.3736))
print("Điểm dốc=0: x≈-0.3736, y' =", slope(-0.3736))

y'(3) = 1462.0
Điểm dốc=0: x≈+0.3736, y' = -0.0005713701248168945
Điểm dốc=0: x≈-0.3736, y' = -0.0005713701248168945


# Bài Tập Về Nhà 02 :
Tạo một tensor ban đầu có giá trị là 2 
Định nghĩa hàm số và tính gradient 
y = x^3 + 2x^2 + 5x + 1
hãy tính dy/dx tại giá trị của x 
Dùng phương pháp Gradient Desccent với Learning rate alpha = 0.1 để cập nhật giá trị x trong 10 vòng lập

In [ ]:
import torch

alpha = 0.1
so_vong = 10
x = torch.tensor(2.0, requires_grad=True)
y = x**3 + 2*x**2 + 5*x + 1
y.backward()
print("Ban đầu: x =", x.item(), "| dy/dx =", x.grad.item())
for i in range(1, so_vong + 1):
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()
    grad = x.grad.item()
    with torch.no_grad():
        x -= alpha * x.grad
    x.grad.zero_()
    print(f"Vòng {i:02d}: x = {x.item():.6f} | dy/dx = {grad:.6f}")

Ban đầu: x = 2.0 | dy/dx = 25.0
Vòng 01: x = -3.000000 | dy/dx = 50.000000
Vòng 02: x = -5.000000 | dy/dx = 20.000000
Vòng 03: x = -11.000000 | dy/dx = 60.000000
Vòng 04: x = -43.400002 | dy/dx = 324.000000
Vòng 05: x = -591.608093 | dy/dx = 5482.080566
Vòng 06: x = -105355.507812 | dy/dx = 1047638.937500
Vòng 07: x = -3329998336.000000 | dy/dx = 33298927616.000000
Vòng 08: x = -3326666712958369792.000000 | dy/dx = 33266667679339511808.000000
Vòng 09: x = -3320013366952489364115158725096898560.000000 | dy/dx = 33200134303350193755266287999320588288.000000
Vòng 10: x = -inf | dy/dx = inf


# Bài Tập Về Nhà 03 :
Tạo một tập dữ liệu giả lập với x là số giờ học ( ngẫu nhiên từ 1 - 10 ) và y là số điểm được tính theo công thức y  =3x + 5 + noise
Với noise là một giá trị ngẫu nhiên nhỏ 

1. Khởi tạo tham số w va b nhẫu nhiên với requires_grad = True
2. Tính MSE
3. Tính Gradient 
4. Cập nhật tham số w và b bằng Gradient Desccent với Learning rate alpha = 0.01
5. Lặp lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình .

In [ ]:
import torch
torch.manual_seed(42)
n = 50
x = torch.randint(1, 11, (n, 1), dtype=torch.float32)   # giờ học 1..10
noise = torch.randn(n, 1) * 0.5                          # nhiễu nhỏ
y = 3 * x + 5 + noise

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)
alpha = 0.01

for epoch in range(1, 101):
    y_hat = w * x + b                    # dự đoán
    loss = ((y_hat - y) ** 2).mean()     # 2) MSE
    loss.backward()                      # 3) Gradient
    with torch.no_grad():                # 4) Update
        w -= alpha * w.grad
        b -= alpha * b.grad
    w.grad.zero_()                       # reset grad
    b.grad.zero_()

    if epoch % 10 == 0 or epoch == 1:    # 5) xem hội tụ
        print(f"Epoch {epoch:03d} | MSE={loss.item():.4f} | w={w.item():.4f} | b={b.item():.4f}")

print("\nKết quả cuối: w ~", w.item(), " | b ~", b.item())


Epoch 001 | MSE=743.8687 | w=2.8037 | b=-0.0630
Epoch 010 | MSE=5.0757 | w=3.6921 | b=0.2473
Epoch 020 | MSE=4.7027 | w=3.6646 | b=0.4379
Epoch 030 | MSE=4.3583 | w=3.6381 | b=0.6210
Epoch 040 | MSE=4.0403 | w=3.6127 | b=0.7969
Epoch 050 | MSE=3.7468 | w=3.5882 | b=0.9660
Epoch 060 | MSE=3.4758 | w=3.5648 | b=1.1284
Epoch 070 | MSE=3.2257 | w=3.5422 | b=1.2844
Epoch 080 | MSE=2.9948 | w=3.5206 | b=1.4344
Epoch 090 | MSE=2.7816 | w=3.4997 | b=1.5784
Epoch 100 | MSE=2.5848 | w=3.4797 | b=1.7168

Kết quả cuối: w ~ 3.4797468185424805  | b ~ 1.7168469429016113


In [48]:
# Pytorch with Tensor

In [5]:
import torch 
import numpy as np


In [6]:
torch.__version__

'2.9.1+cpu'

In [7]:
#Chuyển đổi mảng numpy sang tensor pytorch
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type(arr))


[1 2 3 4 5]
int64
<class 'numpy.ndarray'>


In [8]:
x =torch.from_numpy(arr)
print(x.dtype)

torch.int64


In [9]:
print(x.type())

torch.LongTensor


In [10]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [11]:
x2 = torch.from_numpy(arr2)
print(x2)
print(x2.type())

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)
torch.DoubleTensor


In [12]:
# copy and shring 

x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [13]:
arr[0] =99
print(x)

tensor([99,  2,  3,  4,  5])


In [14]:
arr = np.array([0,5])
x = torch.tensor(arr)
print(x)

tensor([0, 5])


# Bài Tập Về Nhà 04 : 
Giải thích 2 trường hợp trên (một cái có thể thay thế được 99, một cái không).
## Giải Thích :
Trong trường hợp 1 khi dùng hàm torch.from_numpy(arr) với mục đích là tạo ra một Tensor đống vai trò như một lớp vỏ bao bọc vùng bộ nhớ của mảng Numpy. Khác với trường hợp 2 khi dùng hàm torch.tensor(arr) là tạo một vùng bộ nhớ hoàn toàn mới và sao chép toàn bộ giá trị từ mảng Numpy sang vùng bộ nhớ đó

Nên khi thực hiện arr[0] 99 với 2 trường hợp cho ra kết quả khác nhau, với trường hợp 1 là đang dùng chung một bộ nhớ, trường hợp 2 là đang dùng tensor cũ.


# Bài Tập Về Nhà 05 : 
Bạn giúp thầy tạo tensor với
1. empty 
2. zeros
3. ones
4. random
5. Reshape với view và view as

In [17]:
import torch

# Công nghệ: PyTorch (torch) - Tensor API + reshape (view, view_as)

# 1) empty
a = torch.empty(2, 3)
print("empty:\n", a)

# 2) zeros
b = torch.zeros(2, 3)
print("\nzeros:\n", b)

# 3) ones
c = torch.ones(2, 3)
print("\nones:\n", c)

# 4) random
d = torch.rand(2, 3)
print("\nrandom:\n", d)

# 5) reshape với view và view_as
e = torch.arange(1, 13)      # 1..12
e_view = e.view(3, 4)        # view
mau = torch.zeros(2, 6)
e_view_as = e.view_as(mau)   # view_as

print("\nview(3,4):\n", e_view)
print("\nview_as(2,6):\n", e_view_as)


empty:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

zeros:
 tensor([[0., 0., 0.],
        [0., 0., 0.]])

ones:
 tensor([[1., 1., 1.],
        [1., 1., 1.]])

random:
 tensor([[0.6431, 0.3908, 0.6947],
        [0.0897, 0.8712, 0.1330]])

view(3,4):
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])

view_as(2,6):
 tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])
