# DEEP LEARNING
## TUẦN 2: NUMPY, PANDAS, MATPLOTLIB

In [1]:
# Numpy là thư viện kiểu list
# Vì:
# + numpy nhanh 
# + có nhiều hàm tích hợp dễ sử dụng cho AI
# để sử dụng numpy thì: pip install numpy
import numpy as np

In [2]:
# thử tạo 1 list numpy
python_list = ([1,2,3,4,5])

#chuyển đổi danh sách trên thành numpy list
numpy_list = np.array(python_list)
type(numpy_list)

numpy.ndarray

In [3]:
# list trong python có thể hỗ trợ nhiều loại dữ liệu trong list
my_list = [1, "chào", True, 2.0]

In [5]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [8]:
# chuyển đổi kiểu dữ liệu 
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [ ]:
# accessing và indexing
x = np.array([1,2,3,4,5,6,7,8])# np.array(range(1,9))


In [10]:
x[3]

np.int64(4)

In [ ]:
# lấy nhiều hơn 1 phần tử
# công thức [start:end:step]
x[0:3]

array([1, 2, 3])

In [ ]:
# lấy từ 3 - 8 theo 3 cách
# cacah 1
x[2:8]


array([3, 4, 5, 6, 7, 8])

In [ ]:
# cách 2
x[2:]

array([3, 4, 5, 6, 7, 8])

In [ ]:
# cách 3- không đúng
x[2:-1]

array([3, 4, 5, 6, 7, 8])

In [ ]:
# lấy số 3 vầ số 5
x[2], x[4]
x[2:5:2]

array([3, 5])

In [26]:
# đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [27]:
data = [[1,2], [3,4], [5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [39]:
# lấy số 2 
np_list[0,1]

np.int64(2)

In [40]:
# lấy số 6
np_list[2,1]

np.int64(6)

In [41]:
# layass 3 4 5 6 
np_list[1:, :]

array([[3, 4],
       [5, 6]])

In [ ]:
# cách 2
np_list[[1,2]]


array([[3, 4],
       [5, 6]])

In [53]:
# cách3
np_list[1:3]

array([[3, 4],
       [5, 6]])

In [54]:
#cách 4
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [57]:
# lấy 1 3 5 
np_list[:,0]

array([1, 3, 5])

In [60]:
np_list[::2,0]

array([1, 5])

In [64]:
x = [[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12],
        [13,14,15,16]
]
np_list = np.array(x)
np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [67]:
# layass 2 6 10 14
np_list[:,1]


array([ 2,  6, 10, 14])

In [69]:
# layass 7 và 11
np_list[1:3,2]

array([ 7, 11])

In [82]:
# lấy 4 7 10
np_list[[0,1,2],[3,2,1]]

array([ 4,  7, 10])

In [ ]:
# lấy 16 15 14 13
np_list[[3,3,3,3],[3,2,1,0]]
np_list[-1, ::-1]

array([16, 15, 14, 13])

In [90]:
np_list[-1, -1::-1]


array([16, 15, 14, 13])

# BTVN thú vị

# cho ma trận = [[99,99,99],
                [99,99,99],
                [99,99,99]]

# hãy tưởng tượng ô 99 trống 
# giả sử  0 là o
# giả sử 1 là x
# lấy đầu vào từ phía x và phí o luôn phiên 
# Nếu đầu vào từ phía X là (0,0)
# ma trận sẽ trở thành 

# [x,99,99]
# [99,99,99]
# [99,99,99]
# nếu đầu vào từ phía o cũng là (0,0)
# thông báo nhập lại 
# nếu không thì điền vào ma trận

# thử thách: nếu người đầu tiên có 3 phần tử liên tiếp thì dùng trò chơi


# BTVN 2
# cho y = [[1,2,3],[4,5,6],[7,8,9]]

# LẤY 4 5 6
# lấy 2, 5
# lấy 3,4
# lấy 9,6,3


# BTVN 3

# cho x  = [[1,2,3,4,5,6,7,8,9,10]]

# xuata ra cas gias trị chẵn sử dụng if
# xuất ra các giá trị chẵn sử dụng lit comprehension
# 

In [91]:
np_x = np.arange(10)
np_x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [93]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [95]:
idx = [True, True,  True, False,  True, True,  True, False,  True, False]
np_x[idx]

array([0, 1, 2, 4, 5, 6, 8])

In [96]:
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# BTVN4
# tạo 1 mảng numpy có kích thức 150 x 5. giả sử mảng này chứa 150 mẫu dữ liệu 
# của sinh vienen  bao gồm chiều cao cân nặng tuổi , luonmgw và điểm trung bình
# tách mảng dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y
# tách mảng X thành X train X test trong đó X train chứa 70% dữ liệu và tahcs y thành y train và y test trong đó y train chứa 70% dữ leieuj
# tạo 10 tập dữ liệu không chồng chéo nhau

In [1]:
import numpy as np

# 1. Tạo mảng dữ liệu 150 x 5
# Giả lập dữ liệu sinh viên
np.random.seed(42)  # để kết quả có thể tái lập

height = np.random.randint(150, 190, size=150)     # chiều cao (cm)
weight = np.random.randint(45, 90, size=150)       # cân nặng (kg)
age = np.random.randint(18, 25, size=150)           # tuổi
salary = np.random.randint(5, 30, size=150) * 1e6   # lương (VNĐ)
gpa = np.round(np.random.uniform(2.0, 4.0, size=150), 2)  # điểm TB

data = np.column_stack((height, weight, age, salary, gpa))

print("Kích thước mảng dữ liệu:", data.shape)

# 2. Tách X và y
X = data[:, :4]   # 4 cột đầu
y = data[:, 4]    # cột cuối

print("Shape X:", X.shape)
print("Shape y:", y.shape)

# 3. Chia train / test (70% - 30%)
num_samples = X.shape[0]
train_size = int(0.7 * num_samples)

# Trộn dữ liệu
indices = np.random.permutation(num_samples)

train_indices = indices[:train_size]
test_indices = indices[train_size:]

X_train = X[train_indices]
X_test = X[test_indices]

y_train = y[train_indices]
y_test = y[test_indices]

print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

# 4. Tạo 10 tập dữ liệu không chồng chéo
# Mỗi tập gồm 15 mẫu (150 / 10)
num_folds = 10
fold_size = num_samples // num_folds

folds = []

for i in range(num_folds):
    start = i * fold_size
    end = start + fold_size
    fold = data[start:end]
    folds.append(fold)

# Kiểm tra
print("\nSố tập dữ liệu:", len(folds))
print("Kích thước mỗi tập:", folds[0].shape)


Kích thước mảng dữ liệu: (150, 5)
Shape X: (150, 4)
Shape y: (150,)
X_train shape: (105, 4)
X_test shape: (45, 4)
y_train shape: (105,)
y_test shape: (45,)

Số tập dữ liệu: 10
Kích thước mỗi tập: (15, 5)
